print ("ESTE PROGRAMA SIRVE PARA SACAR EL PROMEDIO DE 5 CALIFICACIONES")
MAT =int (input("INGRESA TU MATRICULA:"))
CAL1 =float (input("INGRESA LA 1RA CALIFICACION:"))
CAL2 =float (input("INGRESA LA 2RA CALIFICACION:"))
CAL3 =float (input("INGRESA LA 3RA CALIFICACION:"))
CAL4 =float (input("INGRESA LA 4RA CALIFICACION:"))
CAL5 =float (input("INGRESA LA 5RA CALIFICACION:"))
PROM = (CAL1 + CAL2 + CAL3 + CAL4 + CAL5) /5
print(f"TU MATRICULA ES:{MAT} TU PROMEDIO ES:{PROM}")
